version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t danko/docker-react -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: |
            docker run -e CI=true danko/docker-react npm run test

  deploy:
    steps:
      - checkout
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            aws elasticbeanstalk create-application-version --application-name docker --version-label $CIRCLE_SHA1 --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$BUCKET_PATH/$CIRCLE_SHA1.zip
            aws elasticbeanstalk update-environment --application-name docker --environment-name Docker-env --version-label $CIRCLE_SHA1
    
    environment:
      BUCKET_NAME: "Docker-react-env.eba-ppinm2wi.us-east-1.elasticbeanstalk.com"
      BUCKET_PATH: "docker"
