version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Build Docker image
          command: |
            docker build -t danko/docker-react -f Dockerfile.dev .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
