version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: |
            sudo service docker start
            docker build -t danko/docker-react -f Dockerfile.dev .

      - run:
          name: Run Tests
          command: docker run -e CI=true danko/docker-react npm run test

      # Other steps and commands related to your CI/CD process

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

