version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t danko/docker-react -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: |
            docker run -e CI=true danko/docker-react npm run test

      - deploy:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            aws configure set aws_access_key_id YOUR_ACCESS_KEY
            aws configure set aws_secret_access_key YOUR_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
            aws elasticbeanstalk create-application-version --application-name YOUR_APPLICATION_NAME --version-label YOUR_VERSION_LABEL --source-bundle S3Bucket=elasticbeanstalk-us-east-1-284204458350,S3Key=YOUR_FILE_NAME
            aws elasticbeanstalk update-environment --environment-name docker-react --version-label YOUR_VERSION_LABEL
