version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com | sudo sh
      - run:
          name: Build Docker image
          command: |
            docker build -t danko/docker-react -f Dockerfile.dev .
      - run:
          name: Run tests
          command: |
            docker run danko/docker-react npm run test -- --coverage
