version: 2.1
jobs:
  build:
    docker:
      - image: node:14.17.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t danko/docker-react -f Dockerfile.dev .
      - run:
          name: Run tests
          command: |
            docker run danko/docker-react npm run test -- --coverage
