version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get -y install docker-compose

      - run:
          name: Build and Run Tests
          command: |
            docker-compose -f docker-compose.dev.yml up --build --abort-on-container-exit

      # Other steps and commands related to your CI/CD process

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

