version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t danko/docker-react -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: |
            docker run -e CI=true danko/docker-react npm run test
  deploy:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            aws configure set default.region us-east-1
            aws elasticbeanstalk create-application-version --application-name docker --version-label $CIRCLE_SHA1 --source-bundle S3Bucket=elasticbeanstalk-us-east-1-284204458350,S3Key=docker-react/$CIRCLE_SHA1.zip
            aws elasticbeanstalk update-environment --environment-name Docker-react-env --version-label $CIRCLE_SHA1
            access_key_id: $AWS_ACCESS_KEY
            secret_access_key:
              secure: "AWS_SECRET_KEY"
